baseurl = "http://blog.fraixed.es"
theme = "archie"
languageCode = "en-us"
copyright = "This works is license under a Creative Commons Attribution-ShareAlike 4.0 International license"
title = "Ivan Fraixedes' Blog"

# Content
builddrafts = false

[pagination]
pageSize = 1000

[markup]
  [markup.highlight]
  style = "catppuccin-mocha"

[permalinks]
post = "/post/:filename"

[params]
subtitle = "Software / System Engineering & personal random thoughts / theories"
description = "Opinionated Software Engineering & Development, Tech Community, Start-ups, personal random thoughts & theories, and whatever I'd like to write about ;P"
author = "Ivan Fraixedes"

mode ="toggle" # color-mode → light,dark,toggle or auto
useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
mathjax = false # disable MathJax support
katex = false # disable KaTeX support

  [[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://bit.ly/ifraixedes_blog_gh"

  [[params.social]]
  name = "X"
  icon = "x"
  url = "https://bit.ly/ifraixedes_blog_x"

  [[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://bit.ly/ifraixedes_blog_lk"
