baseurl = "http://blog.fraixed.es"
theme = "archie"
languageCode = "en-us"
copyright = "This works is license under a Creative Commons Attribution-ShareAlike 4.0 International license"
title = "Ivan Fraixedes' Blog"

# Content
builddrafts = false
paginate = 1000


[markup]
  [markup.highlight]
  style = "catppuccin-mocha"

[permalinks]
post = "/post/:filename"

[params]
author = "Ivan Fraixedes"
mode ="toggle" # color-mode → light,dark,toggle or auto
useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = "Software / System Engineering, hacks & personal thoughts"
mathjax = false # disable MathJax support
katex = false # disable KaTeX support

  [[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://bit.ly/ifraixedes_blog_gh"

  [[params.social]]
  name = "X"
  icon = "x"
  url = "https://bit.ly/ifraixedes_blog_x"

  [[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://bit.ly/ifraixedes_blog_lk"

# [params]
#   locale = "en_US"
#   subtitle = "Soft. Engineering, dev, hacks & thoughts"
#   description = "Opinionated Software Engineering & Dev Stuff, hacks, Tech Community and Start-ups and a bit of personal thoughts & theories"
#   disqus_shortname = "blog-ifraixedes"
#   year = 2015
#   author_name = "Ivan Fraixedes"
#   author_url = "http://ivan.fraixed.es"
#   social_image = "https://avatars0.githubusercontent.com/u/1731633"
#   twitter_username = "ifraixedes"
#   [[params.social_profiles]]
#     name = "t"
#     description = "Follow me!!"
#     url = "https://twitter.com/ifraixedes"
#   [[params.social_profiles]]
#     name = "lk"
#     description = "LinkedIn"
#     url = "https://uk.linkedin.com/in/ifraixedes"
#   [[params.social_profiles]]
#     name = "g+"
#     description = "Follow me!!"
#     url = "https://plus.google.com/+IvanFraixedes"

[services]
  [services.googleAnalytics]
  # ID = "UA-54405610-2" # Disabled temporary, although I'm not thinking to enable it back
