baseurl = "http://blog.fraixed.es"
theme = "ifraixedes"
languageCode = "en-gb"
copyright = "This works is license under a Creative Commons Attribution-ShareAlike 4.0 International license"
title = "Ivan Fraixedes' Blog"
buildfrafts = false
canonifyurls = false
pygmentsstyle = "colorful"

[blackfriday]
  fractions = false

[permalinks]
  post = "/post/:filename"

[params]
  subtitle = "Soft. Engineering, dev, hacks & thoughts"
  description = "Opinionated Software Engineering & Dev Stuff, hacks, Tech Community and Start-ups and a bit of personal thoughts & theories"
  disqusShortname = "blog-ifraixedes"
  year = 2015
  authorName = "Ivan Fraixedes"
  authorURL = "http://ivan.fraixed.es" # Optional: you can ommit and author name will never be linked
  contact_email = "xxxx@domain.com"
  social_image = "https://avatars0.githubusercontent.com/u/1731633" # Optional: you can ommmit this variable if you don't want `<meta name="og:image"` as default in the pages which is not specified
  twitter_username = "ifraixedes"
  [[params.social_profiles]]
    name = "t"
    description = "Follow me!!"
    url = "https://twitter.com/ifraixedes"
  [[params.social_profiles]]
    name = "lk"
    description = "LinkedIn"
    url = "http://linkedin.com/"
  [[params.social_profiles]]
    name = "g+"
    description = "Follow me!!"
    url = "http://plus.google.com"
  [[params.social_profiles]]
    name = "fb"
    description = "Facebook"
    url = "http://facebook.com/XXXXXXXXXX"
