baseurl = "http://blog.fraixed.es"
theme = "fraixedes"
languageCode = "en-gb"
copyright = "This works is license under a Creative Commons Attribution-ShareAlike 4.0 International license"
title = "Ivan Fraixedes' Blog"
buildfrafts = false
canonifyurls = false
pygmentsstyle = "colorful"

[blackfriday]
  fractions = false

[permalinks]
  post = "/post/:filename"

[params]
  locale = "en_GB"
  subtitle = "Soft. Engineering, dev, hacks & thoughts"
  description = "Opinionated Software Engineering & Dev Stuff, hacks, Tech Community and Start-ups and a bit of personal thoughts & theories"
  disqusShortname = "blog-ifraixedes"
  googleAnalytics = "UA-54405610-2"
  year = 2015
  authorName = "Ivan Fraixedes"
  authorURL = "http://ivan.fraixed.es"
  social_image = "https://avatars0.githubusercontent.com/u/1731633"
  twitter_username = "ifraixedes"
  [[params.social_profiles]]
    name = "t"
    description = "Follow me!!"
    url = "https://twitter.com/ifraixedes"
  [[params.social_profiles]]
    name = "lk"
    description = "LinkedIn"
    url = "https://uk.linkedin.com/in/ifraixedes"
  [[params.social_profiles]]
    name = "g+"
    description = "Follow me!!"
    url = "https://plus.google.com/+IvanFraixedes"
